-- Insert MBTI Types
INSERT INTO website_mbtitype (mbti_type_id, mbti_type) VALUES
    (1, 'INTJ'),
    (2, 'INTP'),
    (3, 'ENTJ'),
    (4, 'ENTP'),
    (5, 'INFJ'),
    (6, 'INFP'),
    (7, 'ENFJ'),
    (8, 'ENFP'),
    (9, 'ISTJ'),
    (10, 'ISFJ'),
    (11, 'ESTJ'),
    (12, 'ESFJ'),
    (13, 'ISTP'),
    (14, 'ISFP'),
    (15, 'ESTP'),
    (16, 'ESFP');

-- Insert Movies
INSERT INTO website_movie (title, description, release_date, image, first_preference_id, second_preference_id, third_preference_id) VALUES
    ('Inception', 'A mind-bending thriller about dream manipulation.', '2010-07-16', 'movie_images/inception.jpg', 1, 4, 2),
    ('The Shawshank Redemption', 'A story of hope and resilience in prison.', '1994-09-23', 'movie_images/shawshank_redemption.jpg', 5, 10, 9),
    ('The Matrix', 'A hacker discovers the truth about his reality.', '1999-03-31', 'movie_images/the_matrix.jpg', 13, 2, 8),
    ('Forrest Gump', 'A unique man lives an extraordinary life.', '1994-07-06', 'movie_images/forrest_gump.jpg', 6, 10, 16),
    ('The Dark Knight', 'Batman faces his greatest challenge against the Joker.', '2008-07-18', 'movie_images/the_dark_knight.jpg', 3, 9, 7),
    ('Interstellar', 'A space exploration mission to save humanity.', '2014-11-07', 'movie_images/interstellar.jpg', 5, 1, 4),
    ('The Godfather', 'A powerful tale of family and crime in America.', '1972-03-24', 'movie_images/the_godfather.jpg', 9, 11, 3),
    ('Pulp Fiction', 'An intertwining story of crime and redemption.', '1994-10-14', 'movie_images/pulp_fiction.jpg', 8, 15, 13),
    ('Spirited Away', 'A sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.', '2003-03-28', 'movie_images/spirited_away.jpg', 6, 8, 14),
    ('Parasite', 'Greed and class discrimination threaten the relationship between a family and a clan.', '2019-11-08', 'movie_images/parasite.jpg', 1, 5, 3),
    ('Whiplash', 'A promising young drummer and his struggles.', '2014-10-15', 'movie_images/whiplash.jpg', 4, 7, 12),
    ('The Prestige', 'Rival 19th-century magicians engage in a bitter battle for trade secrets.', '2006-10-20', 'movie_images/the_prestige.jpg', 15, 11, 3),
    ('Casablanca', 'A cafe owner struggles to help his former lover escape the Nazis.', '1943-01-23', 'movie_images/casablanca.jpg', 5, 14, 9),
    ('American Beauty', 'A father has a mid-life crisis after becoming infatuated with his daughter''s best friend.', '1999-10-01', 'movie_images/am_beau.jpg', 9, 11, 3),
    ('Ikiru', 'A bureaucrat tries to find meaning in his life after he discovers he has terminal cancer.', '1956-03-25', 'movie_images/ikiru.jpg', 10, 16, 13),
    ('Spider-Man: Into the Spider-Verse', 'Teen Miles Morales becomes the Spider-Man of his universe.', '2008-12-14', 'movie_images/itsv.jpg', 3, 2, 11),
    ('The Shining', 'A family heads to an isolated hotel, where a sinister presence influences the father into violence.', '1980-06-13', 'movie_images/shining.jpg', 15, 4, 7),
    ('Inglourious Basterds', 'A plan to assassinate Nazi leaders by a group of Jewish soldiers coincides with a theatre owner''s vengeful plans.', '2009-08-21', 'movie_images/basterds.jpg', 1, 12, 4),
    ('UP', '78-year-old Carl Fredricksen travels to South America in his house equipped with balloons.', '2009-07-23', 'movie_images/up.jpg', 5, 6, 10),
    ('Good Will Hunting', 'Will Hunting, a janitor at MIT, has a gift for mathematics.', '1998-01-09', 'movie_images/hunting.jpg', 3, 15, 12),
    ('3 Idiots', 'Two friends are searching for their long lost companion and revisit their college days.', '2009-12-25', 'movie_images/threeidiots.jpg', 11, 4, 8),
    ('Requiem for a Dream', 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.', '2000-12-15', 'movie_images/requiem.jpg', 10, 13, 7),
    ('Amelie', 'A young waitress Amelie decides to help people find happiness.', '2002-02-08', 'movie_images/amelie.jpg', 14, 4, 9),
    ('Oppenheimer', 'A dramatization of the life story of J. Robert Oppenheimer.', '2023-07-21', 'movie_images/oppenheimer.jpg', 12, 1, 5),
    ('Eternal Sunshine of the Spotless Mind', 'A couple undergoes a medical procedure to have each other erased from their memories forever.', '2004-03-19', 'movie_images/eternal.jpg', 6, 11, 4),
    ('Ratatouille', 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.', '2007-06-27', 'movie_images/ratatouille.jpg', 13, 15, 2),
    ('Vertigo', 'A detective juggles his personal demons and becoming obsessed with the woman he has been hired to trail.', '1958-05-28', 'movie_images/vertigo.jpg', 7, 9, 3),
    ('Taare Zameen Par', 'An 8-year-old boy and the new art teacher who has the compassion to discover the real problem behind his struggles in school.', '2007-12-21', 'movie_images/taare.jpg', 4, 13, 6),
    ('Scarface', 'A Cuban immigrant becomes the biggest drug smuggler in Florida.', '1983-12-09', 'movie_images/scarface.jpg', 3, 10, 7),
    ('The Grand Budapest Hotel', 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy.', '2014-03-28', 'movie_images/budapest.jpg', 5, 13, 7),
    ('Gladiator', 'A betrayed Roman general fights his way back to glory in the arena.', '2000-05-05', 'movie_images/gladiator.jpg', 3, 9, 11),
    ('The Lion King', 'A lion prince is born, exiled, and returns to reclaim his kingdom.', '1994-06-24', 'movie_images/lionking.jpg', 8, 10, 6),
    ('Shutter Island', 'A U.S. Marshal investigates the disappearance of a patient from a mental hospital.', '2010-02-19', 'movie_images/shutter.jpg', 1, 7, 13),
    ('The Social Network', 'The story of the creation of Facebook and its controversies.', '2010-10-01', 'movie_images/network.jpg', 4, 6, 12),
    ('The Wolf of Wall Street', 'The rise and fall of a corrupt stockbroker.', '2013-12-25', 'movie_images/wolfwall.jpg', 15, 11, 8),
    ('Coco', 'A young musician embarks on a journey to the Land of the Dead.', '2017-11-22', 'movie_images/coco.jpg', 6, 12, 8),
    ('The Avengers', 'Earth’s mightiest heroes assemble to save the world from Loki.', '2012-05-04', 'movie_images/avengers.jpg', 3, 13, 7),
    ('Black Panther', 'A king returns home to defend his kingdom and legacy.', '2018-02-16', 'movie_images/panther.jpg', 8, 9, 15),
    ('Toy Story', 'Toys come to life and face challenges together.', '1995-11-22', 'movie_images/toy.jpg', 14, 5, 10),
    ('Joker', 'The origin story of one of the most infamous villains.', '2019-10-04', 'movie_images/joker.jpg', 6, 4, 13),
    ('La La Land', 'A jazz musician and an aspiring actress fall in love.', '2016-12-09', 'movie_images/lalaland.jpg', 7, 14, 12),
    ('Avatar', 'A marine on an alien planet sides with the natives in their struggle for survival.', '2009-12-18', 'movie_images/avatar.jpg', 5, 3, 8),
    ('The Silence of the Lambs', 'An FBI trainee seeks help from a brilliant but psychotic inmate.', '1991-02-14', 'movie_images/lamb.jpg', 1, 11, 9),
    ('Inside Out', 'A young girl’s emotions struggle to guide her through a life change.', '2015-06-19', 'movie_images/inside.jpg', 7, 8, 2),
    ('WALL·E', 'A robot meets another robot and falls in love with her.', '2008-06-27', 'movie_images/wall_e.jpg', 5, 11, 15);
