INSERT INTO website_Book (title, author, description, publication_year, image, first_preference_id, second_preference_id, third_preference_id)
VALUES
('The Alchemist', 'Paulo Coelho', 'A tale about following your dreams and discovering your destiny.', '1988-05-01', 'book_images/the_alchemist.jpg', 1, 2, 3),
('To Kill a Mockingbird', 'Harper Lee', 'A story of racial injustice and childhood innocence in the American South.', '1960-07-11', 'book_images/to_kill_a_mockingbird.jpg', 4, 5, 6),
('1984', 'George Orwell', 'A dystopian novel about surveillance and totalitarianism.', '1949-06-08', 'book_images/1984.jpg', 7, 8, 9),
('Pride and Prejudice', 'Jane Austen', 'A romantic novel exploring the manners and morals of early 19th century England.', '1813-01-28', 'book_images/pride_and_prejudice.jpg', 10, 11, 12),
('The Great Gatsby', 'F. Scott Fitzgerald', 'A tragic tale of wealth, ambition, and unrequited love.', '1925-04-10', 'book_images/the_great_gatsby.jpg', 13, 14, 15),
('The Diary of a Young Girl', 'Anne Frank', 'Anne Frank\'s remarkable diary, a powerful reminder of the horrors of war.', '1947-01-01', 'book_images/annefrank.jpg', 15, 3, 10),
('Animal Farm', 'George Orwell', 'A farm is taken over by its overworked, mistreated animals.', '1945-08-17', 'book_images/animalfarm.jpg', 10, 13, 5),
('The Little Prince', 'Antoine de Saint-Exupéry', 'A pilot stranded in the desert awakes one morning to see the most extraordinary little fellow.', '1943-01-01', 'book_images/prince.jpg', 7, 14, 5),
('The Book Thief', 'Markus Zusak', 'It is 1939. Nazi Germany. Death has never been busier, and will be busier still.', '2005-09-01', 'book_images/thief.jpg', 6, 8, 4),
('The Kite Runner', 'Khaled Hosseini', 'Twelve-year-old Amir is desperate to win the local kite-fighting tournament and his loyal friend Hassan promises to help him.', '2003-05-29', 'book_images/kite.jpg', 10, 13, 1),
('Little Women', 'Louisa May Alcott', 'A day-to-day life story of the March sisters.', '1868-09-30', 'book_images/little.jpg', 6, 8, 9),
('The Priory of the Orange Tree', 'Samantha Shannon', 'An epic feminist fantasy filled with dragons and political intrigue.', '2019-02-26', 'book_images/orangetree.jpg', 3, 6, 9),
('Vicious', 'V.E. Schwab', 'A dark, action-packed tale of superpowers and revenge.', '2013-09-24', 'book_images/vicious.jpg', 7, 8, 14),
('City of Bones', 'Cassandra Clare', 'A young girl discovers her magical heritage and embarks on a dangerous journey.', '2007-03-27', 'book_images/citybone.jpg', 6, 13, 11),
('The 5th Wave', 'Rick Yancey', 'A gripping post-apocalyptic survival story with an alien invasion.', '2013-05-07', 'book_images/fifth.jpg', 12, 9, 4),
('Legend', 'Marie Lu', 'A dystopian novel about two teens on opposite sides of society.', '2011-11-29', 'book_images/legend.jpg', 10, 8, 3),
('An Ember in the Ashes', 'Sabaa Tahir', 'A Roman-inspired fantasy about rebellion and resilience.', '2015-04-28', 'book_images/emberinthe.jpg', 13, 11, 6),
('The Night Circus', 'Erin Morgenstern', 'A magical love story set in a mysterious circus.', '2011-09-13', 'book_images/nightcircus.jpg', 7, 6, 12),
('Caraval', 'Stephanie Garber', 'A dark, enchanting tale of a magical competition.', '2017-01-31', 'book_images/caraval.jpg', 14, 10, 8),
('The Hunger Games', 'Suzanne Collins', 'A dystopian survival story featuring a brutal competition.', '2008-09-14', 'book_images/hungergames.jpg', 5, 13, 9),
('The Cruel Prince', 'Holly Black', 'A dark fairy tale filled with political intrigue and danger.', '2018-01-02', 'book_images/cruelprince.jpg', 11, 7, 4),
('Throne of Glass', 'Sarah J. Maas', 'An assassin seeks redemption in a deadly competition.', '2012-08-07', 'book_images/tog.jpg', 8, 15, 9),
('Children of Blood and Bone', 'Tomi Adeyemi', 'A West African-inspired fantasy about magic and rebellion.', '2018-03-06', 'book_images/bloodbone.jpg', 6, 10, 14),
('Piranesi', 'Susanna Clarke', 'Piranesi\'s house is no ordinary building; but Piranesi is not afraid.', '2020-09-15', 'book_images/piranesi.jpg', 8, 12, 11),
('The Grace Year', 'Kim Liggett', 'A dystopian story of survival and freedom in a patriarchal society.', '2019-10-08', 'book_images/graceyear.jpg', 9, 3, 6),
('Ace of Spades', 'Faridah Àbíké-Íyímídé', 'A dark, thrilling mystery with a social commentary.', '2021-06-01', 'book_images/aceofspades.jpg', 4, 7, 13),
('We Were Liars', 'E. Lockhart', 'A suspenseful and twist-filled novel about family secrets.', '2014-05-13', 'book_images/liars.jpg', 11, 6, 15),
('Scythe', 'Neal Shusterman', 'A thrilling story about morality in a utopian future.', '2016-11-22', 'book_images/scythe.jpg', 3, 8, 14),
('Shadow and Bone', 'Leigh Bardugo', 'A young girl discovers her hidden power and faces a dark enemy.', '2012-06-05', 'book_images/shadowbone.jpg', 7, 10, 9),
('Six of Crows', 'Leigh Bardugo', 'A thrilling heist story with a diverse and dynamic crew.', '2015-09-29', 'book_images/sixofcrows.jpg', 12, 14, 6),
('The Atlas Six', 'Olivie Blake', 'A dark academic fantasy about a secret society of magical scholars.', '2020-01-25', 'book_images/atlassix.jpg', 9, 5, 11),
('Lessons in Chemistry', 'Bonnie Garmus', 'A tale of a female scientist in the 1960s.', '2022-03-01', 'book_images/chemistry.jpg', 11, 10, 4),
('People We Meet on Vacation', 'Emily Henry', 'A friends-to-lovers romantic comedy.', '2021-05-11', 'book_images/peoplemeet.jpg', 8, 15, 7),
('Normal People', 'Sally Rooney', 'The complex entanglements of Connell and Marianne.', '2018-08-28', 'book_images/normalpeople.jpg', 14, 6, 10),
('Red Queen', 'Victoria Aveyard', 'A fantasy novel about a divided world of Reds and Silvers.', '2015-02-10', 'book_images/redqueen.jpg', 3, 8, 9),
('Babel', 'R.F. Kuang', 'A dark academic exploration of language and empire.', '2022-08-23', 'book_images/babel.jpg', 9, 4, 6),
('Tomorrow, and Tomorrow, and Tomorrow', 'Gabrielle Zevin', 'A tale of friendship and creativity in the world of video game design.', '2022-07-05', 'book_images/tomorrow.jpg', 11, 7, 3),
('The Paris Library', 'Janet Skeslien Charles', 'A dual-timeline novel centered around the American Library in Paris during WWII.', '2021-02-09', 'book_images/parislibrary.jpg', 12, 10, 5),
('A Man Called Ove', 'Fredrik Backman', 'A heartwarming story about an irritable old man and his unexpected friendships.', '2012-08-27', 'book_images/ove.jpg', 14, 9, 6),
('Pachinko', 'Min Jin Lee', 'A multigenerational story of a Korean family living in Japan.', '2017-02-07', 'book_images/pachinko.jpg', 8, 10, 15),
('The Dutch House', 'Ann Patchett', 'A story of siblings and their shared history in their family home.', '2019-09-24', 'book_images/dutchhou.jpg', 4, 13, 8),
('The Nightingale', 'Kristin Hannah', 'A tale of two sisters set during World War II.', '2015-02-03', 'book_images/thenightingale.jpg', 5, 7, 12),
('Where the Crawdads Sing', 'Delia Owens', 'A murder mystery intertwined with a coming-of-age story.', '2018-08-14', 'book_images/crawdadssing.jpg', 6, 13, 11),
('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'An aging Hollywood star reveals her glamorous and scandalous past.', '2017-06-13', 'book_images/evelynhugo.jpg', 4, 8, 14),
('A Court of Thorns and Roses', 'Sarah J. Maas', 'A dark, romantic fantasy set in a magical world.', '2015-05-05', 'book_images/courtthorn.jpg', 10, 15, 13),
('Daisy Jones & The Six', 'Taylor Jenkins Reid', 'The rise and fall of a fictional 70s rock band.', '2019-03-05', 'book_images/daisyjones.jpg', 8, 14, 9),
('Circe', 'Madeline Miller', 'A retelling of the Greek mythological figure Circe.', '2018-04-10', 'book_images/circe.jpg', 5, 10, 4),
('The Song of Achilles', 'Madeline Miller', 'A beautiful love story set during the Trojan War.', '2011-09-20', 'book_images/songofachilles.jpg', 6, 11, 5),
('The Midnight Library', 'Matt Haig', 'A library containing books showing different versions of one’s life.', '2020-08-20', 'book_images/midnightlibrary.jpg', 7, 15, 12),
('The House in the Cerulean Sea', 'TJ Klune', 'A heartwarming fantasy about family and acceptance.', '2020-03-17', 'book_images/cerulean.jpg', 8, 6, 13),
('The Great Gatsby', 'F. Scott Fitzgerald', 'A tragic tale of wealth, ambition, and unrequited love.', '1925-04-10', 'book_images/gatsby.jpg', 13, 14, 15);

