# Generated by Django 5.1.2 on 2024-12-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='watchlistitem',
            table='mbti_rec_watchlistitem',
        ),
    ]
