# Generated by Django 5.1.2 on 2024-12-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_watchlistitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='watchlistitem',
            table=None,
        ),
    ]
