# Generated by Django 5.1.3 on 2024-12-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_referral'),
        ('website', '0004_personalizedlist_personalizedbook_personalizedmovie'),
    ]

    operations = [
    ]
