# Generated by Django 5.1.2 on 2025-01-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_merge_20241207_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
